kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sam-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Ingress HTTP
        hostPort: 8080
        protocol: TCP
      - containerPort: 443  # Ingress HTTPS
        hostPort: 8443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true,fluxcd.io/ready=true"
    extraMounts:
      - hostPath: /tmp/kind/volumes/pgdata
        containerPath: /mnt/data/pgdata
      - hostPath: /tmp/kind/volumes/minio
        containerPath: /mnt/data/minio

  - role: worker
    extraMounts:
      - hostPath: /tmp/kind/volumes/artifacts
        containerPath: /mnt/data/artifacts
      - hostPath: /tmp/kind/volumes/scanner
        containerPath: /mnt/data/scanner

  - role: worker
    extraMounts:
      - hostPath: /tmp/kind/volumes/grafana
        containerPath: /mnt/data/grafana
      - hostPath: /tmp/kind/volumes/loki
        containerPath: /mnt/data/loki